version: "3"
services:
  wordpress:
    container_name: "wordpress"
    build:
      dockerfile: ./docker/wordpress/Dockerfile
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html

  db:
    container_name: "db"
    build:
      dockerfile: ./docker/db/Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: qweqwe
      MYSQL_DATABASE: wp
      MYSQL_USER: user
      MYSQL_PASSWORD: qweqwe
    volumes:
      - ./docker/db/data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      - db
    ports:
      - 8089:80
