version: "3"
services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: qweqwe
      WORDPRESS_DEBUG: 1
    volumes:
      - ./html:/var/www/html

  db:
    container_name: "db"
    build:
      dockerfile: ./docker/db/Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: qweqwe
      MYSQL_DATABASE: wp
      MYSQL_USER: user
      MYSQL_PASSWORD: qweqwe
    volumes:
      - ./docker/db/data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      - db
    ports:
      - 8089:80
